### ISSUE TITLE
update yq default version to 4.x

### ISSUE THREAD

**Issue by agentschmitt** [SamhammerAG/setup-yq#1]
the helm action https://github.com/SamhammerAG/helm-action/releases/tag/v2 now requires yq version 4.x
so we should probably switch the default version of yq also to some 4.x version

it could also be that we dont need to use this action anymore, when yq 4 is already preinstalled.
but not sure for selfhosted runners... so maybe still a release would be saver.
https://github.com/chrisdickinson/setup-yq/pull/9#issuecomment-1309345850

**Comment by devRoemer** [comment]
default changed to 4.40.5
